subdomains:
  - https://gist.githubusercontent.com/jhaddix/86a06c5dc309d08580a018c66354a056/raw/96f4e51d96b2203f19f6381c8c545b278eaa0837/all.txt
  - https://gist.githubusercontent.com/six2dez/a307a04a222fab5a57466c51e1569acf/raw
  - https://paper.vulsee.com/Dictionary-Of-Pentesting/Subdomain/subnames-880199.txt
  - https://raw.githubusercontent.com/0xPugal/fuzz4bounty/refs/heads/master/DNS/permutations.txt
  - https://raw.githubusercontent.com/0xPugal/fuzz4bounty/refs/heads/master/DNS/subdomains.txt
  - https://raw.githubusercontent.com/assetnote/commonspeak2-wordlists/master/subdomains/subdomains.txt
  - https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_huge.txt
  - https://raw.githubusercontent.com/netsecurity-as/subfuz/master/subdomain_megalist.txt
  - https://raw.githubusercontent.com/pentester-io/commonspeak/master/httparchive/output/compiled/2017_10_22_subdomains.txt
  - https://raw.githubusercontent.com/pentester-io/commonspeak/master/stackoverflow/output/compiled/stackoverflow_2017_10_22.urls_subdomains.txt
  - https://raw.githubusercontent.com/rbsec/dnscan/master/subdomains.txt
  - https://raw.githubusercontent.com/tamimhasan404/Wordlist404/refs/heads/main/Subdomain-Brute-Force/subdomain-bruteforce.txt
  - https://raw.githubusercontent.com/TheRook/subbrute/master/names.txt
  - https://raw.githubusercontent.com/Tim1512/subdomain_scanner/master/wordlist/s-10000.txt
  - https://raw.githubusercontent.com/trickest/wordlists/main/inventory/subdomains.txt
  - https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt
  - https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt