generic:
  - https://raw.githubusercontent.com/six2dez/OneListForAll/refs/heads/main/dict/dotfiles_short.txt
  - https://raw.githubusercontent.com/xmendez/wfuzz/refs/heads/master/wordlist/general/admin-panels.txt
  - https://raw.githubusercontent.com/aels/subdirectories-discover/refs/heads/main/dsplusleakypaths.txt
  - https://raw.githubusercontent.com/Bo0oM/fuzz.txt/refs/heads/master/fuzz.txt
  - https://raw.githubusercontent.com/ayoubfathi/leaky-paths/refs/heads/main/leaky-paths.txt
  - https://raw.githubusercontent.com/xmendez/wfuzz/refs/heads/master/wordlist/general/common.txt
  - https://raw.githubusercontent.com/xmendez/wfuzz/refs/heads/master/wordlist/general/megabeast.txt
  - https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Discovery/Web-Content/directory-list-2.3-medium.txt
  - https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Discovery/Web-Content/raft-medium-words.txt
  - https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Discovery/Web-Content/raft-large-directories.txt
  - https://raw.githubusercontent.com/six2dez/OneListForAll/refs/heads/main/dict/dir_short.txt
  - https://raw.githubusercontent.com/xajkep/wordlists/refs/heads/master/discovery/top-10k-web-directories_from_10M_urlteam_links.txt

subdomains:
  - https://gist.githubusercontent.com/jhaddix/86a06c5dc309d08580a018c66354a056/raw/96f4e51d96b2203f19f6381c8c545b278eaa0837/all.txt
  - https://gist.githubusercontent.com/six2dez/a307a04a222fab5a57466c51e1569acf/raw
  - https://paper.vulsee.com/Dictionary-Of-Pentesting/Subdomain/subnames-880199.txt
  - https://raw.githubusercontent.com/0xPugal/fuzz4bounty/refs/heads/master/DNS/permutations.txt
  - https://raw.githubusercontent.com/0xPugal/fuzz4bounty/refs/heads/master/DNS/subdomains.txt
  - https://raw.githubusercontent.com/assetnote/commonspeak2-wordlists/master/subdomains/subdomains.txt
  - https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_huge.txt
  - https://raw.githubusercontent.com/netsecurity-as/subfuz/master/subdomain_megalist.txt
  - https://raw.githubusercontent.com/pentester-io/commonspeak/master/httparchive/output/compiled/2017_10_22_subdomains.txt
  - https://raw.githubusercontent.com/pentester-io/commonspeak/master/stackoverflow/output/compiled/stackoverflow_2017_10_22.urls_subdomains.txt
  - https://raw.githubusercontent.com/rbsec/dnscan/master/subdomains.txt
  - https://raw.githubusercontent.com/tamimhasan404/Wordlist404/refs/heads/main/Subdomain-Brute-Force/subdomain-bruteforce.txt
  - https://raw.githubusercontent.com/TheRook/subbrute/master/names.txt
  - https://raw.githubusercontent.com/Tim1512/subdomain_scanner/master/wordlist/s-10000.txt
  - https://raw.githubusercontent.com/trickest/wordlists/main/inventory/subdomains.txt
  - https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt
  - https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt
  - https://raw.githubusercontent.com/carlospolop/Auto_Wordlists/refs/heads/main/wordlists/bf_directories.txt
  - https://raw.githubusercontent.com/th3cyb3rhub/subscout/refs/heads/main/subdomains-wordlist.txt
